spring.application.name=api-gateway
server.port=8080

# Eureka Client Configuration
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

# Spring Cloud Gateway Routing
spring.cloud.gateway.mvc.routes[0].id=auth-service
spring.cloud.gateway.mvc.routes[0].uri=lb://auth-service
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/auth/**

# Security Configuration for Gateway
spring.main.web-application-type=servlet
